Repository crossplane-contrib/provider-upjet-aws, pull requests merged in 2022-11, with the labels that each got.

#103 Add Glue SecurityConfiguration
  apis/glue/v1beta1/zz_generated.deepcopy.go
  apis/glue/v1beta1/zz_generated.managed.go
  apis/glue/v1beta1/zz_generated.managedlist.go
  apis/glue/v1beta1/zz_generated.resolvers.go
  apis/glue/v1beta1/zz_generated_terraformed.go
  apis/glue/v1beta1/zz_securityconfiguration_types.go
  config/externalname.go
  config/glue/config.go
  examples-generated/glue/securityconfiguration.yaml
  examples/glue/securityconfiguration.yaml
  internal/controller/glue/securityconfiguration/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/glue.aws.upbound.io_securityconfigurations.yaml
Labels: size/XXL

#126 glue: regenerate to get update
  internal/controller/glue/securityconfiguration/zz_controller.go
Labels: size/XS

#127 Remove updoc Makefile target
  Makefile
Labels: size/S

#128 Remove UXP requirement notice
  docs/Configuration.md
Labels: size/S

#137 Moving appmesh (1) resource to v1beta1 version
  apis/appmesh/v1beta1/zz_generated.deepcopy.go
  apis/appmesh/v1beta1/zz_generated.managed.go
  apis/appmesh/v1beta1/zz_generated.managedlist.go
  apis/appmesh/v1beta1/zz_generated_terraformed.go
  apis/appmesh/v1beta1/zz_groupversion_info.go
  apis/appmesh/v1beta1/zz_mesh_types.go
  apis/zz_register.go
  config/externalname.go
  config/externalnamenottested.go
  examples-generated/appmesh/mesh.yaml
  examples/appmesh/mesh.yaml
  internal/controller/appmesh/mesh/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/appmesh.aws.upbound.io_meshes.yaml
Labels: size/XXL

#141 Fix Uptest timeout annotation
  examples/cloudsearch/domain.yaml
  examples/ec2/instance.yaml
  examples/eks/cluster.yaml
  examples/eks/identityproviderconfig.yaml
Labels: size/S

#133 Moving configservice (7) resources to v1beta1 version
  apis/configservice/v1beta1/zz_awsconfigurationrecorderstatus_types.go
  apis/configservice/v1beta1/zz_configrule_types.go
  apis/configservice/v1beta1/zz_configurationaggregator_types.go
  apis/configservice/v1beta1/zz_configurationrecorder_types.go
  apis/configservice/v1beta1/zz_conformancepack_types.go
  apis/configservice/v1beta1/zz_deliverychannel_types.go
  apis/configservice/v1beta1/zz_generated.deepcopy.go
  apis/configservice/v1beta1/zz_generated.managed.go
  apis/configservice/v1beta1/zz_generated.managedlist.go
  apis/configservice/v1beta1/zz_generated.resolvers.go
  apis/configservice/v1beta1/zz_generated_terraformed.go
  apis/configservice/v1beta1/zz_groupversion_info.go
  apis/configservice/v1beta1/zz_remediationconfiguration_types.go
  apis/zz_register.go
  config/externalname.go
  config/externalnamenottested.go
  examples-generated/configservice/awsconfigurationrecorderstatus.yaml
  examples-generated/configservice/configrule.yaml
  examples-generated/configservice/configurationaggregator.yaml
  examples-generated/configservice/configurationrecorder.yaml
  examples-generated/configservice/conformancepack.yaml
  examples-generated/configservice/deliverychannel.yaml
  examples-generated/configservice/remediationconfiguration.yaml
  examples/configservice/awsconfigurationrecorderstatus.yaml
  examples/configservice/configrule.yaml
  examples/configservice/configurationaggregator.yaml
  examples/configservice/configurationrecorder.yaml
  examples/configservice/conformancepack.yaml
  examples/configservice/deliverychannel.yaml
  examples/configservice/remediationconfiguration.yaml
  internal/controller/configservice/awsconfigurationrecorderstatus/zz_controller.go
  internal/controller/configservice/configrule/zz_controller.go
  internal/controller/configservice/configurationaggregator/zz_controller.go
  internal/controller/configservice/configurationrecorder/zz_controller.go
  internal/controller/configservice/conformancepack/zz_controller.go
  internal/controller/configservice/deliverychannel/zz_controller.go
  internal/controller/configservice/remediationconfiguration/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/configservice.aws.upbound.io_awsconfigurationrecorderstatuses.yaml
  package/crds/configservice.aws.upbound.io_configrules.yaml
  package/crds/configservice.aws.upbound.io_configurationaggregators.yaml
  package/crds/configservice.aws.upbound.io_configurationrecorders.yaml
  package/crds/configservice.aws.upbound.io_conformancepacks.yaml
  package/crds/configservice.aws.upbound.io_deliverychannels.yaml
  package/crds/configservice.aws.upbound.io_remediationconfigurations.yaml
Labels: size/XXL

#139 Make not-generated Terraform resources CSV available as a Github workflow artifact
  .github/workflows/ci.yml
  cmd/generator/main.go
  go.mod
  go.sum
Labels: size/M

#145 Consume upjet commit 6de200a3a8b0ac77c5f9d122f93db26aacd61960
  go.mod
  go.sum
Labels: size/XS

#143 Fixes and Tweaks with Uptest related targets
  Makefile
  cluster/test/setup.sh
Labels: size/M

#140 Configurable maxConcurrentReconciles and pollInterval with sensible defaults
  cmd/provider/main.go
Labels: size/S

#110 fix(asg): fix observed failed availability_zones / vpc_zone_identifier
  apis/autoscaling/v1beta1/zz_generated_terraformed.go
  config/autoscaling/config.go
Labels: size/XS, community

#147 Add 6 aws appmesh services
  apis/appmesh/v1beta1/zz_gatewayroute_types.go
  apis/appmesh/v1beta1/zz_generated.deepcopy.go
  apis/appmesh/v1beta1/zz_generated.managed.go
  apis/appmesh/v1beta1/zz_generated.managedlist.go
  apis/appmesh/v1beta1/zz_generated.resolvers.go
  apis/appmesh/v1beta1/zz_generated_terraformed.go
  apis/appmesh/v1beta1/zz_mesh_types.go
  apis/appmesh/v1beta1/zz_route_types.go
  apis/appmesh/v1beta1/zz_virtualgateway_types.go
  apis/appmesh/v1beta1/zz_virtualnode_types.go
  apis/appmesh/v1beta1/zz_virtualrouter_types.go
  apis/appmesh/v1beta1/zz_virtualservice_types.go
  config/externalname.go
  config/externalnamenottested.go
  examples-generated/appmesh/gatewayroute.yaml
  examples-generated/appmesh/route.yaml
  examples-generated/appmesh/virtualgateway.yaml
  examples-generated/appmesh/virtualnode.yaml
  examples-generated/appmesh/virtualrouter.yaml
  examples-generated/appmesh/virtualservice.yaml
  examples/appmesh/gatewayroute.yaml
  examples/appmesh/route.yaml
  examples/appmesh/virtualgateway.yaml
  examples/appmesh/virtualnode.yaml
  examples/appmesh/virtualrouter.yaml
  examples/appmesh/virtualservice.yaml
  internal/controller/appmesh/gatewayroute/zz_controller.go
  internal/controller/appmesh/route/zz_controller.go
  internal/controller/appmesh/virtualgateway/zz_controller.go
  internal/controller/appmesh/virtualnode/zz_controller.go
  internal/controller/appmesh/virtualrouter/zz_controller.go
  internal/controller/appmesh/virtualservice/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/appmesh.aws.upbound.io_gatewayroutes.yaml
  package/crds/appmesh.aws.upbound.io_routes.yaml
  package/crds/appmesh.aws.upbound.io_virtualgateways.yaml
  package/crds/appmesh.aws.upbound.io_virtualnodes.yaml
  package/crds/appmesh.aws.upbound.io_virtualrouters.yaml
  package/crds/appmesh.aws.upbound.io_virtualservices.yaml
Labels: size/XXL

#199 Updates in the Quickstart Guide
  docs/Quickstart.md
  docs/quickstart.sh
Labels: backport release-0.21

#153 Moving EC2 (2) resources to v1beta1 version#27
  apis/ec2/v1beta1/zz_generated.deepcopy.go
  apis/ec2/v1beta1/zz_generated.managed.go
  apis/ec2/v1beta1/zz_generated.managedlist.go
  apis/ec2/v1beta1/zz_generated.resolvers.go
  apis/ec2/v1beta1/zz_generated_terraformed.go
  apis/ec2/v1beta1/zz_snapshotcreatevolumepermission_types.go
  apis/ec2/v1beta1/zz_transitgatewaypeeringattachmentaccepter_types.go
  config/externalname.go
  config/externalnamenottested.go
  examples-generated/ec2/snapshotcreatevolumepermission.yaml
  examples-generated/ec2/transitgatewaypeeringattachmentaccepter.yaml
  examples/ec2/snapshotcreatevolumepermission.yaml
  examples/ec2/testhooks/delete-snapshot-permissions.sh
  examples/ec2/transitgatewaypeeringattachmentaccepter.yaml
  internal/controller/ec2/snapshotcreatevolumepermission/zz_controller.go
  internal/controller/ec2/transitgatewaypeeringattachmentaccepter/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/ec2.aws.upbound.io_snapshotcreatevolumepermissions.yaml
  package/crds/ec2.aws.upbound.io_transitgatewaypeeringattachmentaccepters.yaml
Labels: size/XL, v1beta1-migration

#161 Issue 8
  apis/cur/v1beta1/zz_generated.deepcopy.go
  apis/cur/v1beta1/zz_generated.managed.go
  apis/cur/v1beta1/zz_generated.managedlist.go
  apis/cur/v1beta1/zz_generated.resolvers.go
  apis/cur/v1beta1/zz_generated_terraformed.go
  apis/cur/v1beta1/zz_groupversion_info.go
  apis/cur/v1beta1/zz_reportdefinition_types.go
  apis/dataexchange/v1beta1/zz_dataset_types.go
  apis/dataexchange/v1beta1/zz_generated.deepcopy.go
  apis/dataexchange/v1beta1/zz_generated.managed.go
  apis/dataexchange/v1beta1/zz_generated.managedlist.go
  apis/dataexchange/v1beta1/zz_generated.resolvers.go
  apis/dataexchange/v1beta1/zz_generated_terraformed.go
  apis/dataexchange/v1beta1/zz_groupversion_info.go
  apis/dataexchange/v1beta1/zz_revision_types.go
  apis/datapipeline/v1beta1/zz_generated.deepcopy.go
  apis/datapipeline/v1beta1/zz_generated.managed.go
  apis/datapipeline/v1beta1/zz_generated.managedlist.go
  apis/datapipeline/v1beta1/zz_generated_terraformed.go
  apis/datapipeline/v1beta1/zz_groupversion_info.go
  apis/datapipeline/v1beta1/zz_pipeline_types.go
  apis/zz_register.go
  config/cur/config.go
  config/externalname.go
  config/externalnamenottested.go
  config/provider.go
  examples-generated/cur/reportdefinition.yaml
  examples-generated/dataexchange/dataset.yaml
  examples-generated/dataexchange/revision.yaml
  examples-generated/datapipeline/pipeline.yaml
  examples/configservice/configurationaggregator.yaml
  examples/configservice/remediationconfiguration.yaml
  examples/cur/reportdefinition.yaml
  examples/dataexchange/dataset.yaml
  examples/dataexchange/revision.yaml
  examples/datapipeline/pipeline.yaml
  internal/controller/cur/reportdefinition/zz_controller.go
  internal/controller/dataexchange/dataset/zz_controller.go
  internal/controller/dataexchange/revision/zz_controller.go
  internal/controller/datapipeline/pipeline/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/cur.aws.upbound.io_reportdefinitions.yaml
  package/crds/dataexchange.aws.upbound.io_datasets.yaml
  package/crds/dataexchange.aws.upbound.io_revisions.yaml
  package/crds/datapipeline.aws.upbound.io_pipelines.yaml
Labels: size/XXL

#160 fix(client): include crossplane in useragent
  cluster/images/provider-aws/Dockerfile
  internal/clients/provider_config.go
Labels: size/XS
