Repository crossplane-contrib/provider-upjet-aws, pull requests merged in 2022-10, with the labels that each got.

#80 Remove Marketplace self-reference.
  package/crossplane.yaml
Labels: size/XS

#83 readme: add badges
  README.md
Labels: size/XS

#84 Fetch submodule after checkout
  .github/workflows/uptest.yml
Labels: size/XS

#88 Update remaining versions in docs
  docs/Quickstart.md
Labels: size/S

#89 Remove kuttl input from cluster_dump target
  Makefile
Labels: size/XS

#95 Only run e2e tests if commenter is a member of Upbound org
  .github/workflows/uptest.yml
Labels: size/XS

#94 Clean up github workflows
  .github/workflows/ci.yml
  .github/workflows/uptest-all.yml
  .github/workflows/uptest.yml
  apis/generate.go
  go.mod
  go.sum
Labels: size/M

#91 Configure codecommit group and add examples
  .gitignore
  Makefile
  apis/codecommit/v1beta1/zz_approvalruletemplate_types.go
  apis/codecommit/v1beta1/zz_approvalruletemplateassociation_types.go
  apis/codecommit/v1beta1/zz_generated.deepcopy.go
  apis/codecommit/v1beta1/zz_generated.managed.go
  apis/codecommit/v1beta1/zz_generated.managedlist.go
  apis/codecommit/v1beta1/zz_generated.resolvers.go
  apis/codecommit/v1beta1/zz_generated_terraformed.go
  apis/codecommit/v1beta1/zz_groupversion_info.go
  apis/codecommit/v1beta1/zz_repository_types.go
  apis/codecommit/v1beta1/zz_trigger_types.go
  apis/zz_register.go
  config/externalname.go
  config/externalnamenottested.go
  examples-generated/codecommit/approvalruletemplate.yaml
  examples-generated/codecommit/approvalruletemplateassociation.yaml
  examples-generated/codecommit/repository.yaml
  examples-generated/codecommit/trigger.yaml
  examples/codecommit/approvalruletemplateassociation.yaml
  examples/codecommit/testhooks/delete-trigger.sh
  examples/codecommit/trigger.yaml
  internal/controller/codecommit/approvalruletemplate/zz_controller.go
  internal/controller/codecommit/approvalruletemplateassociation/zz_controller.go
  internal/controller/codecommit/repository/zz_controller.go
  internal/controller/codecommit/trigger/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/codecommit.aws.upbound.io_approvalruletemplateassociations.yaml
  package/crds/codecommit.aws.upbound.io_approvalruletemplates.yaml
  package/crds/codecommit.aws.upbound.io_repositories.yaml
  package/crds/codecommit.aws.upbound.io_triggers.yaml
Labels: size/XXL

#102 Configure codedeploy group, codepipeline group and add examples
  apis/codepipeline/v1beta1/zz_codepipeline_types.go
  apis/codepipeline/v1beta1/zz_generated.deepcopy.go
  apis/codepipeline/v1beta1/zz_generated.managed.go
  apis/codepipeline/v1beta1/zz_generated.managedlist.go
  apis/codepipeline/v1beta1/zz_generated.resolvers.go
  apis/codepipeline/v1beta1/zz_generated_terraformed.go
  apis/codepipeline/v1beta1/zz_groupversion_info.go
  apis/codepipeline/v1beta1/zz_webhook_types.go
  apis/deploy/v1beta1/zz_app_types.go
  apis/deploy/v1beta1/zz_deploymentconfig_types.go
  apis/deploy/v1beta1/zz_deploymentgroup_types.go
  apis/deploy/v1beta1/zz_generated.deepcopy.go
  apis/deploy/v1beta1/zz_generated.managed.go
  apis/deploy/v1beta1/zz_generated.managedlist.go
  apis/deploy/v1beta1/zz_generated.resolvers.go
  apis/deploy/v1beta1/zz_generated_terraformed.go
  apis/deploy/v1beta1/zz_groupversion_info.go
  apis/zz_register.go
  config/externalname.go
  config/externalnamenottested.go
  examples-generated/codepipeline/codepipeline.yaml
  examples-generated/codepipeline/webhook.yaml
  examples-generated/deploy/app.yaml
  examples-generated/deploy/deploymentconfig.yaml
  examples-generated/deploy/deploymentgroup.yaml
  examples/codepipeline/webhook.yaml
  examples/deploy/app.yaml
  examples/deploy/deploymentconfig.yaml
  examples/deploy/deploymentgroup.yaml
  internal/controller/codepipeline/codepipeline/zz_controller.go
  internal/controller/codepipeline/webhook/zz_controller.go
  internal/controller/deploy/app/zz_controller.go
  internal/controller/deploy/deploymentconfig/zz_controller.go
  internal/controller/deploy/deploymentgroup/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/codepipeline.aws.upbound.io_codepipelines.yaml
  package/crds/codepipeline.aws.upbound.io_webhooks.yaml
  package/crds/deploy.aws.upbound.io_apps.yaml
  package/crds/deploy.aws.upbound.io_deploymentconfigs.yaml
  package/crds/deploy.aws.upbound.io_deploymentgroups.yaml
Labels: size/XXL

#107 Configure codestarconnections group, codestarnotifications group and add examples
  apis/codestarconnections/v1beta1/zz_connection_types.go
  apis/codestarconnections/v1beta1/zz_generated.deepcopy.go
  apis/codestarconnections/v1beta1/zz_generated.managed.go
  apis/codestarconnections/v1beta1/zz_generated.managedlist.go
  apis/codestarconnections/v1beta1/zz_generated_terraformed.go
  apis/codestarconnections/v1beta1/zz_groupversion_info.go
  apis/codestarconnections/v1beta1/zz_host_types.go
  apis/codestarnotifications/v1beta1/zz_generated.deepcopy.go
  apis/codestarnotifications/v1beta1/zz_generated.managed.go
  apis/codestarnotifications/v1beta1/zz_generated.managedlist.go
  apis/codestarnotifications/v1beta1/zz_generated.resolvers.go
  apis/codestarnotifications/v1beta1/zz_generated_terraformed.go
  apis/codestarnotifications/v1beta1/zz_groupversion_info.go
  apis/codestarnotifications/v1beta1/zz_notificationrule_types.go
  apis/zz_register.go
  config/externalname.go
  config/externalnamenottested.go
  examples-generated/codepipeline/codepipeline.yaml
  examples-generated/codestarconnections/connection.yaml
  examples-generated/codestarconnections/host.yaml
  examples-generated/codestarnotifications/notificationrule.yaml
  examples/codestarconnections/connection.yaml
  examples/codestarconnections/host.yaml
  examples/codestarnotifications/notificationrule.yaml
  internal/controller/codestarconnections/connection/zz_controller.go
  internal/controller/codestarconnections/host/zz_controller.go
  internal/controller/codestarnotifications/notificationrule/zz_controller.go
  internal/controller/zz_setup.go
  package/crds/codestarconnections.aws.upbound.io_connections.yaml
  package/crds/codestarconnections.aws.upbound.io_hosts.yaml
  package/crds/codestarnotifications.aws.upbound.io_notificationrules.yaml
Labels: size/XXL
