Repository crossplane-contrib/provider-upjet-aws, pull requests merged in 2024-12, with the labels that each got.

#1599 add subnet_configuration to VPCEndpoint LateInit
  apis/ec2/v1beta1/zz_vpcendpoint_terraformed.go
  apis/ec2/v1beta2/zz_vpcendpoint_terraformed.go
  config/ec2/config.go
  examples/ec2/v1beta1/vpcendpointsubnetassociation.yaml
Labels: backport release-1.18

#1616 Update module golang.org/x/net to v0.33.0 release-1.16 [SECURITY]
  go.mod
  go.sum
Labels: backport release-1.15

#1617 Update module golang.org/x/net to v0.33.0 release-1.14 [SECURITY]
  go.mod
  go.sum
Labels: backport release-1.13
